In [1]:
import pandas as pd
import numpy as np

### NumPy

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv')

In [5]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [6]:
np.ones(5)

array([1., 1., 1., 1., 1.])

### Operations in Vector

In [ ]:
u = np.array([2,4,5,6])
u

In [4]:
v = np.array([1,0,0,2])
v

array([1, 0, 0, 2])

In [5]:
u + v

array([3, 4, 5, 8])

In [6]:
u * v

array([ 2,  0,  0, 12])

In [10]:
def mult (u,v):
    assert u.shape[0] == v.shape[0]

    n = u.shape[0]
    x = 0.0
    for i in range(n):
        x = x + u[i]*v[i]

    return x

In [15]:
a = mult(u,v)
print(a)

14.0


In [16]:
u.dot(v)

np.int64(14)

In [19]:
v


array([1, 0, 0, 2])

In [2]:
U = np.array([[2, 4, 5, 6],
              [1, 2, 1, 2],
              [3, 1, 2, 1]])
U

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [4]:
V = np.array([[1, 3, 4, 1],
              [1, 2, 2, 5],
              [2, 4, 5, 2],
              [1, 1, 4, 1]])
V

array([[1, 3, 4, 1],
       [1, 2, 2, 5],
       [2, 4, 5, 2],
       [1, 1, 4, 1]])

In [5]:
U.dot(V)


array([[22, 40, 65, 38],
       [ 7, 13, 21, 15],
       [ 9, 20, 28, 13]])

### Pandas

In [8]:
df.head()

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

In [13]:
df[['Laptop','CPU','Final Price']].head(5)

Laptop            CPU  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...  Intel Core i5   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...  Intel Celeron   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...  Intel Core i3   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...  Intel Core i7   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...  Intel Core i5   

   Final Price  
0      1009.00  
1       299.00  
2       789.00  
3      1199.00  
4       669.01

In [15]:
df.loc[[12,15]]

Laptop Status Brand Model  \
12  ASUS ROG Strix G15 G513RC-HN088 AMD Ryzen 7 68...    New  Asus   ROG   
15  HP 15S-FQ5013NS Intel Core i5-1235U/8GB/512GB ...    New    HP   15S   

              CPU  RAM  Storage Storage type       GPU  Screen Touch  \
12    AMD Ryzen 7   16      512          SSD  RTX 3050    15.6    No   
15  Intel Core i5    8      512          SSD       NaN    15.6    No   

    Final Price  
12       1199.0  
15        699.0

In [17]:
df[['Storage','Final Price']].head(5)/100

Storage  Final Price
0     5.12      10.0900
1     2.56       2.9900
2     2.56       7.8900
3    10.00      11.9900
4     5.12       6.6901

In [22]:
df[(df['Storage']>=1000)]

Laptop       Status  Brand  \
3     MSI Katana GF66 12UC-082XES Intel Core i7-1270...          New    MSI   
5     MSI Crosshair 17 C12VF-264XES Intel Core i7-12...          New    MSI   
11    MSI Thin GF63 12VE-021XES Intel Core i7-12650H...          New    MSI   
20    MSI Cyborg 15 A12VF-098XES Intel Core i5-12450...          New    MSI   
34    MSI Vector GP77 13VF-022XES Intel Core i7-1370...          New    MSI   
...                                                 ...          ...    ...   
2154  Razer Blade 17 4K 144Hz Intel Core i9-12900H/3...  Refurbished  Razer   
2155  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished  Razer   
2156  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished  Razer   
2157  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished  Razer   
2158  Razer Book 13 Intel Evo Core i7-1165G7/16GB/1T...  Refurbished  Razer   

          Model                CPU  RAM  Storage Storage type       GPU  \
3        Katana      Intel Core i7   16     1000          SSD  RTX 3050   
5     Crosshair      Intel Core i7   32     1000          SSD  RTX 4060   
11         Thin      Intel Core i7   16     1000          SSD  RTX 4050   
20       Cyborg      Intel Core i5   16     1000          SSD  RTX 4060   
34       Vector      Intel Core i7   32     1000          SSD  RTX 4060   
...         ...                ...  ...      ...          ...       ...   
2154      Blade      Intel Core i9   32     1000          SSD  RTX 3080   
2155      Blade      Intel Core i7   16     1000          SSD  RTX 3060   
2156      Blade      Intel Core i7   16     1000          SSD  RTX 3070   
2157      Blade      Intel Core i7   32     1000          SSD  RTX 3080   
2158       Book  Intel Evo Core i7   16     1000          SSD       NaN   

      Screen Touch  Final Price  
3       15.6    No      1199.00  
5       17.3    No      1699.00  
11      15.6    No      1399.00  
20      15.6    No      1249.00  
34      17.3    No      2249.00  
...      ...   ...          ...  
2154    17.3    No      4699.99  
2155    17.3    No      2699.99  
2156    17.3    No      2899.99  
2157    17.3    No      3399.99  
2158    13.4   Yes      1899.99  

[614 rows x 12 columns]

In [21]:
df[(df['Storage']>=1000) & (df['Screen']>=17.3)]

Laptop       Status  Brand  \
5     MSI Crosshair 17 C12VF-264XES Intel Core i7-12...          New    MSI   
34    MSI Vector GP77 13VF-022XES Intel Core i7-1370...          New    MSI   
66    MSI Vector GP77 13VG-021XES Intel Core i7-1370...          New    MSI   
129   MSI Pulse GL76 12UEK-828XES Intel Core i7-1270...          New    MSI   
185   HP OMEN 17-cm2003ns Intel Core i7-13700HX/32GB...          New     HP   
...                                                 ...          ...    ...   
2143  PcCom Revolt One 3070 Intel Core i7-11800H/16G...  Refurbished  PcCom   
2154  Razer Blade 17 4K 144Hz Intel Core i9-12900H/3...  Refurbished  Razer   
2155  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished  Razer   
2156  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished  Razer   
2157  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished  Razer   

          Model            CPU  RAM  Storage Storage type       GPU  Screen  \
5     Crosshair  Intel Core i7   32     1000          SSD  RTX 4060    17.3   
34       Vector  Intel Core i7   32     1000          SSD  RTX 4060    17.3   
66       Vector  Intel Core i7   32     1000          SSD  RTX 4070    17.3   
129       Pulse  Intel Core i7   32     1000          SSD  RTX 3060    17.3   
185        Omen  Intel Core i7   32     1000          SSD  RTX 4060    17.3   
...         ...            ...  ...      ...          ...       ...     ...   
2143     Revolt  Intel Core i7   16     1000          SSD  RTX 3070    17.3   
2154      Blade  Intel Core i9   32     1000          SSD  RTX 3080    17.3   
2155      Blade  Intel Core i7   16     1000          SSD  RTX 3060    17.3   
2156      Blade  Intel Core i7   16     1000          SSD  RTX 3070    17.3   
2157      Blade  Intel Core i7   32     1000          SSD  RTX 3080    17.3   

     Touch  Final Price  
5       No      1699.00  
34      No      2249.00  
66      No      2499.00  
129     No      1499.00  
185     No      1799.00  
...    ...          ...  
2143    No      1949.00  
2154    No      4699.99  
2155    No      2699.99  
2156    No      2899.99  
2157    No      3399.99  

[131 rows x 12 columns]

In [28]:
df['CPU'] = df['CPU'].str.replace(' ','_').str.lower()

In [29]:
df.head()

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  intel_core_i5    8      512          SSD       NaN    15.6   
1          Go  intel_celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  intel_core_i3    8      256          SSD       NaN    15.6   
3      Katana  intel_core_i7   16     1000          SSD  RTX 3050    15.6   
4         15S  intel_core_i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

In [32]:
df['Final Price'].describe().round(2)

count    2160.00
mean     1312.64
std       911.48
min       201.05
25%       661.08
50%      1031.95
75%      1708.97
max      7150.47
Name: Final Price, dtype: float64

In [34]:
df['Model'].nunique() # conta os modelos únicos
df['Model'].unique() # mostra os modelos únicos


121

In [37]:
df.isnull().sum()

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64

In [45]:
df.groupby(by='CPU')[['Final Price']].mean().round(2).sort_values(by='Final Price',ascending=True)

Final Price
CPU                               
amd_3015ce                  327.00
intel_celeron               362.51
amd_3020e                   373.53
amd_athlon                  398.83
amd_3015e                   439.83
mediatek_mt8183             458.00
amd_ryzen_3                 489.85
amd_radeon_5                499.00
intel_pentium               504.40
intel_core_i3               532.51
qualcomm_snapdragon_7       577.55
intel_core_m3               683.58
amd_ryzen_5                 732.09
intel_core_i5               888.38
amd_ryzen_7                1155.49
qualcomm_snapdragon_8      1216.78
intel_evo_core_i5          1359.46
apple_m1                   1480.05
microsoft_sq1              1584.78
intel_core_i7              1650.33
intel_evo_core_i7          1908.77
apple_m2                   1911.14
amd_ryzen_9                2481.03
apple_m1_pro               2703.86
apple_m2_pro               2860.54
intel_core_i9              3350.07
intel_evo_core_i9          3699.01
amd_radeon_9               5192.11

### Homework 2024

In [48]:
df.head()

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

In [47]:
# Q2:
df.count()

# R: 2160

Laptop          2160
Status          2160
Brand           2160
Model           2160
CPU             2160
RAM             2160
Storage         2160
Storage type    2118
GPU              789
Screen          2156
Touch           2160
Final Price     2160
dtype: int64

In [49]:
# Q3:
df[['Brand']].nunique()

# R: 27 brands

Brand    27
dtype: int64

In [54]:
# Q4:
df.isnull().sum() > 0

# R: 3 columns

Laptop          False
Status          False
Brand           False
Model           False
CPU             False
RAM             False
Storage         False
Storage type     True
GPU              True
Screen           True
Touch           False
Final Price     False
dtype: bool

In [60]:
# Q5:
df[(df['Brand'] == 'Dell')]['Final Price'].max()

# R: $3936

np.float64(3936.0)

In [68]:
# Q6:
med = df['Screen'].median()
mode = df['Screen'].mode()[0]

print(f'Median = {med} and Mode = {mode}')

# R: No

Median = 15.6 and Mode = 15.6


Empty DataFrame
Columns: [Laptop, Status, Brand, Model, CPU, RAM, Storage, Storage type, GPU, Screen, Touch, Final Price]
Index: []

In [93]:
df.iloc[[624,1430,1503,1548]]

Laptop Status   Brand  \
624   Acer Extensa 15 EX215-54 Intel Core i5-1135G7/...    New    Acer   
1430  HP ENVY x360 2-in-1 Laptop 15-ew0008np Intel C...    New      HP   
1503  Lenovo IdeaPad Gaming 3 15ACH6 AMD Ryzen 5 560...    New  Lenovo   
1548  Lenovo ThinkPad P15 Gen 2 Intel Core i7-11850H...    New  Lenovo   

         Model            CPU  RAM  Storage Storage type        GPU  Screen  \
624    Extensa  Intel Core i5    8      256          SSD        NaN     NaN   
1430      Envy  Intel Core i7   16      512          SSD   RTX 2050     NaN   
1503   IdeaPad    AMD Ryzen 5   16      512          SSD   RTX 3060     NaN   
1548  ThinkPad  Intel Core i7   16      512          SSD  RTX A2000     NaN   

     Touch  Final Price  
624     No       524.99  
1430   Yes      1863.52  
1503    No      1505.00  
1548    No      2569.00

In [141]:
df[df['Screen'].isnull()]

Laptop Status   Brand  \
624   Acer Extensa 15 EX215-54 Intel Core i5-1135G7/...    New    Acer   
1430  HP ENVY x360 2-in-1 Laptop 15-ew0008np Intel C...    New      HP   
1503  Lenovo IdeaPad Gaming 3 15ACH6 AMD Ryzen 5 560...    New  Lenovo   
1548  Lenovo ThinkPad P15 Gen 2 Intel Core i7-11850H...    New  Lenovo   

         Model            CPU  RAM  Storage Storage type        GPU  Screen  \
624    Extensa  Intel Core i5    8      256          SSD        NaN     NaN   
1430      Envy  Intel Core i7   16      512          SSD   RTX 2050     NaN   
1503   IdeaPad    AMD Ryzen 5   16      512          SSD   RTX 3060     NaN   
1548  ThinkPad  Intel Core i7   16      512          SSD  RTX A2000     NaN   

     Touch  Final Price  
624     No       524.99  
1430   Yes      1863.52  
1503    No      1505.00  
1548    No      2569.00

In [142]:
df2 = df.copy()

In [146]:
df2[df2['Screen'].isnull()]

Empty DataFrame
Columns: [Laptop, Status, Brand, Model, CPU, RAM, Storage, Storage type, GPU, Screen, Touch, Final Price]
Index: []

In [148]:
df2['Screen'] = df2['Screen'].fillna(df['Screen'].mode()[0])

In [149]:
df2['Screen'].median()

np.float64(15.6)

### Q7: REGRESSION SAMPLE

In [3]:
df.head()

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

In [11]:
df_in = df[df['Brand']=='Innjoo'][['RAM','Storage','Screen']]
X = df_in.to_numpy()
X

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [14]:
XTX = X.transpose().dot(X)
XTX

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

In [16]:
INV = np.linalg.inv(XTX)
INV

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

In [21]:
y = np.array([1100, 1300, 800, 900, 1000, 1100])
y

array([1100, 1300,  800,  900, 1000, 1100])

In [25]:
w = (INV.dot(X.transpose())).dot(y)
w.sum()

np.float64(91.2998806299555)